x <- seq(-4, 2, by = .01)
png("pnorm.png")
plot (x, pnorm (x), type = "l", col = "RED", lwd = 3)
y3 <- pnorm (-3)+ dnorm(-3) * (x + 3)+0.5*dnorm(1) * ((x+3) ^ 2)
y0 <- pnorm (0) + dnorm (0) * x + 0.5 * dnorm(1) * (x ^ 2)
lines (x, y3, col = "BLUE", lwd = 2)
lines (x, y0, col = "BLUE", lwd = 2)
dev.off()

png("dnorm.png")
plot (x, dnorm (x), type = "l", ylim = c(0, 1), col = "RED", lwd = 3)
y3 <- dnorm (-3) + 3 * dnorm(-3) * (x + 3)+ dnorm (sqrt (3)) * ((x+3) ^ 2)
y0 <- dnorm (0) + dnorm (sqrt (3))* (x ^ 2)
lines (x, y3, col = "BLUE", lwd = 2)
lines (x, y0, col = "BLUE", lwd = 2)
dev.off()