par(mfrow=c(1,2))
phi <- c(-3,-2,-1.5,-1.25,0,2,3)
esq <- c(1,1,3,3,3,2,2)/100
lbd <- seq(-5,5,by=.0001)
fun <- sapply (lbd, function (l) sum (esq / ((phi - l) ^ 2)))
plot (lbd, fun, type = "l", col = "RED", lwd = 2, ylim=c(0,5), xlim=c(-4,4),  xlab = "lambda", ylab = "h(y)")
abline(h=0)
abline(h=1)
for (l in phi) abline(v=l)
fan <- sapply (lbd, function (l) sum ((esq * (l - phi / 2)) / ((phi - l) ^ 2)  ))
plot(lbd, fan, type = "l", col = "RED", lwd = 2, ylim=c(-5,5), xlim=c(-4,4), xlab = "lambda", ylab = "f(y)")
abline(h=0)
for (l in phi) abline(v=l)
par(mfrow=c(1,2))
